<main class="py-5 container">
    <h1 class="text-center">Ajouter un livre</h1>
    <form class="mt-5" method="post" action="index.php?route=check-add-book">
        <div class="mb-3">
            <label for="title" class="form-label">Titre</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <div class="mb-3">
            <label for="author" class="form-label">Auteur-ice</label>
            <input type="text" class="form-control" id="author" name="author">
        </div>
        <div class="mb-3">
            <label class="form-label" for="description">Description</label>
            <input type="text" class="form-control" id="description" name="description">
        </div>
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
</main>