<main class="p-5">
    <h1 class="text-center">Liste des livres</h1>
    <section class="row g-4 py-5">
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">1984</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">George Orwell</h3>
                <p class="card-text">Un homme lutte contre un régime totalitaire oppressant, où la surveillance, la pensée unique et la répression dominent toute la société.</p>
            </article>
        </div>
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">Hunger Games</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">Suzanne Collins</h3>
                <p class="card-text">Katniss participe à un jeu mortel organisé par un gouvernement autoritaire, défiant l’ordre établi pour survivre et protéger les siens.</p>
            </article>
        </div>
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">Notre Dame de Paris</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">Victor Hugo</h3>
                <p class="card-text">Quasimodo, son amour pour Esmeralda, et le destin tragique de personnages prisonniers des conventions sociales et religieuses du Moyen Âge.</p>
            </article>
        </div>
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">L'alchimiste</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">Paulo Coehlo</h3>
                <p class="card-text">Un berger poursuit sa légende personnelle à travers le désert, apprenant que le véritable trésor réside dans le chemin parcouru.</p>
            </article>
        </div>
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">Orgueil et préjugés</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">Jane Austen</h3>
                <p class="card-text">Elizabeth et Darcy surmontent malentendus, orgueil et préjugés, découvrant l’amour véritable dans une société régie par les apparences.</p>
            </article>
        </div>
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">Les androïdes rêvent-ils de moutons électriques ?</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">Philip K. Dick</h3>
                <p class="card-text">Un chasseur de primes traque des androïdes rebelles, remettant en question la frontière entre l’humain et l’intelligence artificielle.</p>
            </article>
        </div>
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">Le Comte de Monte-Christo</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">Alexandre Dumas</h3>
                <p class="card-text">Trahi et emprisonné à tort, Edmond Dantès devient Monte-Cristo pour se venger de ceux qui ont détruit sa vie.</p>
            </article>
        </div>
        <div class="col-6 col-sm-4 col-md-3">
            <article class="card p-4">
                <h2 class="card-title">Psaume pour les recyclés sauvages</h2>
                <h3 class="card-subtitle mb-2 text-body-secondary">Becky Chambers</h3>
                <p class="card-text">Un moine rencontre un robot philosophe, remettant en cause le sens de la vie, du besoin et de la paix intérieure.</p>
            </article>
        </div>
    </section>
</main>