<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Projet </title>
        <link rel="stylesheet" href="assets/styles/css/style.css">
    </head>
    <body>
        <section class="container">
    <header>
        <h1> THE LEAGUE</h1>
        <nav class="navBar">
            <ul class ="navBar-list">
            <li><a>LES TEAMS</a></li>
            <li><a>LES PLAYERS </a></li>
            <li><a>LES MATCHS </a></li>
        </ul>
        </nav>
    </header>
    <main>
        <p>LES TEAMS DE LA LEAGUE</p>
        <section class="Grid">
            <div class="card">
                <img src="assets/styles/img/twig-angry-owls.png">
                <h2>ANGRY OWLS</h2>
                <p class="para-img">A team of angry owls</p>
                <button>DÉCOUVREZ ANGRY OWLS</button>
            </div>
            <div class="card">
                <img src="assets/styles/img/twig-chatty-parrots.png">
                <h2>CHATTY PARROTS</h2>
                <p class="para-img">A team of chatty parrots</p>
                <button>DÉCOUVREZ CHATTY PARROTS</button>
            </div>
            <div class="card">
                <img src="assets/styles/img/twig-panthers.png">
                <h2>PANTHERS</h2>
                <p class="para-img">A team of panthers</p>
                <button>DÉCOUVREZ PANTHERS</button>
            </div>
            <div class="card">
                <img src="assets/styles/img/twig-sparrow.png">
                <h2>SPARROW</h2>
                <p class="para-img">The spies from the east</p>
                <button>DÉCOUVREZ SPARROW</button>
            </div>
            <div class="card">
                <img src="assets/styles/img/twig-vendetta.png">
                <h2>VENDETTA</h2>
                <p class="para-img">A knack for revenge</p>
                <button>DÉCOUVREZ VENDETTA</button>
            </div>
            
        </section>
    </main>
</section>
    </body>
</html>