
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Choisissez un pseudo</title>
</head>
<body>
    <form action="logic/register.php" method="post">
        <label for="first_name">Prénom :</label>
        <input type="text" id="first_name" name="first_name">
        <br/> <br/>
         <label for="last_name">Nom :</label>
        <input type="text" id="last_name" name="last_name">
         <br/> <br/>
         <label for="email">Email :</label>
        <input type="text" id="email" name="email">
          <br/> <br/>
         <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password">
          <br/> <br/>
        
        <button type="submit">Envoyer</button>
    </form>
   
</body>
</html>

