<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		
		<nav>
		    <a href="index.php">Liste</a>
		    <a href="index.php?route=show_user">Show</a> 
		    <a href="index.php?route=create_user">Create</a> 
		    <a href="index.php?route=update_user">Update</a>
		</nav>
	
		<?php
			if ($route === 'show_user') {
				require 'templates/users/show.phtml';
			} elseif ($route === 'create_user') {
				require 'templates/users/create.phtml';
			} elseif ($route === 'update_user') {
                require 'templates/users/update.phtml';
            } 
			else {
				require 'templates//users/list.phtml';
			}
			
		?>
	</body>
</html>



    
  

    
    
  
  
    
   