<main>
	<h1>Créer un utilisateur</h1>




    <form action="index.php?route=check_create_user" method="post">
        <label for="email">Email :</label><br>
        <input type="email" id="email" name="email"><br>
    
        <label for="first_name">Prénom :</label><br>
        <input type="text" id="first_name" name="first_name"><br>
    
        <label for="last_name">Nom :</label><br>
        <input type="text" id="last_name" name="last_name"><br><br>
    
        <button type="submit">Créer</button>
    </form>


</main>