<main class="container py-5">
    <form>
        <fieldset class="my-1">
            <label for="username" class="form-label">
                <?= $this->translator->translate("choose_username") ?>
            </label>
            <input type="text" name="username" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                <?= $this->translator->translate("enter_email") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
               <?= $this->translator->translate("choose_password") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
             <?= $this->translator->translate("confirm_password") ?>
            </label>
            <input type="password" name="confirm-password" id="confirm-password" class="form-control"/>
        </fieldset>
        <fieldset class="my-4">
            <button type="submit" class="btn btn-primary"> <?= $this->translator->translate("register_button") ?></button>
        </fieldset>
    </form>
    <p>
        <?= $this->translator->translate("already_have_account") ?><a href="index.php"> <?= $this->translator->translate("login_here_button") ?> </a>
    </p>
</main>